const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const CHANGE_THEME = 'CHANGE_THEME';
const HIDE_BASKET = 'HIDE_BASKET';
const FILL_BASKET = 'FILL_BASKET';
const TOGGLE_TOOLTIP = 'TOGGLE_TOOLTIP';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

export const MUTATIONS = {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  CHANGE_THEME,
  HIDE_BASKET,
  FILL_BASKET,
  TOGGLE_TOOLTIP,
  INCREMENT,
  DECREMENT,
};

export const ACTIONS = {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  CHANGE_THEME,
  HIDE_BASKET,
  FILL_BASKET,
  TOGGLE_TOOLTIP,
  INCREMENT,
  DECREMENT,
};
export const TOOLTIP_TYPES = {
  BAG_INTRO: 'BAG_INTRO',
};
export const MEASUREMENT_UNITS = {
  KILOGRAMS: 'kg',
  GRAMS: 'g',
  LITERS: 'l',
  MILLILITERS: 'ml',
};

export const errorMessages = {
  NETWORK_ERROR: 'Network Error',
};
