const ADD_PRODUCT = 'ADD_PRODUCT';
const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const CHANGE_THEME = 'CHANGE_THEME';
const HIDE_BASKET = 'HIDE_BASKET';
const FILL_BASKET = 'FILL_BASKET';
const SET_BACKGROUND = 'SET_BACKGROUND';
const TOGGLE_TOOLTIP = 'TOGGLE_TOOLTIP';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

export const mutations = {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  CHANGE_THEME,
  HIDE_BASKET,
  FILL_BASKET,
  SET_BACKGROUND,
  TOGGLE_TOOLTIP,
  INCREMENT,
  DECREMENT,
};

export const actions = {
  ADD_PRODUCT,
  REMOVE_PRODUCT,
  CHANGE_THEME,
  HIDE_BASKET,
  FILL_BASKET,
  SET_BACKGROUND,
  TOGGLE_TOOLTIP,
  INCREMENT,
  DECREMENT,
};

export const measurementUnits = {
  grams: 'g',
  kilograms: 'kg',
  milliliters: 'ml',
  liters: 'l',
};
